auto_sync = true
update_check = true
# sync_address = "https://api.atuin.sh"

sync_frequency = "5m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
# search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
# filter_mode = "global"

## With workspace filtering enabled, Atuin will filter for commands executed
## in any directory within a git repository tree (default: false)
workspaces = true

style = "auto"

show_preview = true
# word_jump_mode = "emacs"


enter_accept = false

#[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
#common_subcommands = [
#  "cargo",
#  "go",
#  "git",
#  "npm",
#  "yarn",
#  "pnpm",
#  "kubectl",
#]
# 
